name: UI Automation Test CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  ui-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Java
        run: java -version

      - name: Run UI Automation Test
        run: mvn clean test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: target/surefire-reports